spring.application.name=caronrent

# Server
server.port=8080

# local Database

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=dhfvdshjgfskdjfhkfhkadsfjhrbrkwjhajdbfksjhdb
jwt.expiration=86400000

# ID Encryption (32 characters for AES-256)
id.encryption.key=ThisIsASecretKeyForEncryption123

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shubhamkundu1122@gmail.com
spring.mail.password=your app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.otp.expiration-minutes=10

# Logging
logging.level.com.caronrent=DEBUG

# Admin Configuration
app.admin.email=admin@admin.com
app.admin.password=admin

# File upload configuration (for car images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Razorpay Configuration
razorpay.key.id=razorpay key id here
razorpay.key.secret=razorpay secret key here

# JSP View Resolver
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp


# flow of car status
# Payment Status Flow:
# 1. PENDING -> Payment not initiated
# 2. PAID -> Payment successful
# 3. FAILED -> Payment failed
# 4. REFUNDED -> Payment refunded
# 5. CANCELLED -> Payment cancelled

# Booking Status Flow:
# 1. PAYMENT_PENDING -> Waiting for payment
# 2. PAYMENT_CONFIRMED -> Payment done, waiting for owner confirmation
# 3. CONFIRMED -> Owner confirmed the booking
# 4. CANCELLED -> Booking cancelled
# 5. COMPLETED -> Booking completed